package java2.InicialPanel;

import java3.Panels.Painel_Pets_JIFF;
import java3.Panels.Painel_Tutores_JIFF;
import java3.Panels.Painel_Veterinarios_JIFF;


public class Swing_Tela_Inicial extends javax.swing.JFrame {

    public Swing_Tela_Inicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPaneControl = new javax.swing.JDesktopPane();
        BOTAO_CADASTRO_PET___ = new javax.swing.JButton();
        BOTAO_CADASTRO_TUTOR___ = new javax.swing.JButton();
        BOTAO_CADASTRO_VETERINARIO___ = new javax.swing.JButton();
        BOTAO_SAIR___ = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MENU_HEADDER_BUTTON = new javax.swing.JMenu();
        MENU_ITEM_PETS = new javax.swing.JMenuItem();
        MENU_ITEM_TUTORES = new javax.swing.JMenuItem();
        MENU_ITEM_VETERINARIOS = new javax.swing.JMenuItem();
        MENU_ITEM_SAIR = new javax.swing.JMenuItem();
        MENU_HEADDER_PRECOS = new javax.swing.JMenu();
        MENU_ITEM_PRECOS = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 500));

        DesktopPaneControl.setBackground(new java.awt.Color(20, 108, 148));
        DesktopPaneControl.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(176, 218, 255), 2), "  BEM VINDO À TOCA DO LULU  ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Gill Sans Ultra Bold", 1, 24), new java.awt.Color(176, 218, 255))); // NOI18N
        DesktopPaneControl.setPreferredSize(new java.awt.Dimension(900, 450));

        javax.swing.GroupLayout DesktopPaneControlLayout = new javax.swing.GroupLayout(DesktopPaneControl);
        DesktopPaneControl.setLayout(DesktopPaneControlLayout);
        DesktopPaneControlLayout.setHorizontalGroup(
            DesktopPaneControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        DesktopPaneControlLayout.setVerticalGroup(
            DesktopPaneControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        BOTAO_CADASTRO_PET___.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BOTAO_CADASTRO_PET___.setText("Pets");
        BOTAO_CADASTRO_PET___.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAO_CADASTRO_PET___ActionPerformed(evt);
            }
        });

        BOTAO_CADASTRO_TUTOR___.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BOTAO_CADASTRO_TUTOR___.setText("Tutores");
        BOTAO_CADASTRO_TUTOR___.setToolTipText("");
        BOTAO_CADASTRO_TUTOR___.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAO_CADASTRO_TUTOR___ActionPerformed(evt);
            }
        });

        BOTAO_CADASTRO_VETERINARIO___.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BOTAO_CADASTRO_VETERINARIO___.setText("Veterinários");
        BOTAO_CADASTRO_VETERINARIO___.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAO_CADASTRO_VETERINARIO___ActionPerformed(evt);
            }
        });

        BOTAO_SAIR___.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BOTAO_SAIR___.setText("Sair");
        BOTAO_SAIR___.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAO_SAIR___ActionPerformed(evt);
            }
        });

        MENU_HEADDER_BUTTON.setText("Menu");

        MENU_ITEM_PETS.setText("1- Pets");
        MENU_ITEM_PETS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_ITEM_PETSActionPerformed(evt);
            }
        });
        MENU_HEADDER_BUTTON.add(MENU_ITEM_PETS);

        MENU_ITEM_TUTORES.setText("2- Tutores");
        MENU_ITEM_TUTORES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_ITEM_TUTORESActionPerformed(evt);
            }
        });
        MENU_HEADDER_BUTTON.add(MENU_ITEM_TUTORES);

        MENU_ITEM_VETERINARIOS.setText("3- Veterinários");
        MENU_ITEM_VETERINARIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_ITEM_VETERINARIOSActionPerformed(evt);
            }
        });
        MENU_HEADDER_BUTTON.add(MENU_ITEM_VETERINARIOS);

        MENU_ITEM_SAIR.setText("Sair");
        MENU_ITEM_SAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_ITEM_SAIRActionPerformed(evt);
            }
        });
        MENU_HEADDER_BUTTON.add(MENU_ITEM_SAIR);

        jMenuBar1.add(MENU_HEADDER_BUTTON);

        MENU_HEADDER_PRECOS.setText("Opções");

        MENU_ITEM_PRECOS.setText("Preços");
        MENU_HEADDER_PRECOS.add(MENU_ITEM_PRECOS);

        jMenuBar1.add(MENU_HEADDER_PRECOS);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BOTAO_CADASTRO_PET___, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BOTAO_CADASTRO_TUTOR___, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BOTAO_CADASTRO_VETERINARIO___, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BOTAO_SAIR___, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DesktopPaneControl, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DesktopPaneControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(BOTAO_CADASTRO_PET___)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BOTAO_CADASTRO_TUTOR___)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BOTAO_CADASTRO_VETERINARIO___)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BOTAO_SAIR___)
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MENU_ITEM_SAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_ITEM_SAIRActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MENU_ITEM_SAIRActionPerformed

    private void MENU_ITEM_PETSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_ITEM_PETSActionPerformed
        // DesktopPaneControl.removeAll();
        Painel_Pets_JIFF obj = new Painel_Pets_JIFF();
        DesktopPaneControl.add(obj).setVisible(true);
    }//GEN-LAST:event_MENU_ITEM_PETSActionPerformed

    private void MENU_ITEM_TUTORESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_ITEM_TUTORESActionPerformed
        // DesktopPaneControl.removeAll();
        Painel_Tutores_JIFF obj = new Painel_Tutores_JIFF();
        DesktopPaneControl.add(obj).setVisible(true);
    }//GEN-LAST:event_MENU_ITEM_TUTORESActionPerformed

    private void MENU_ITEM_VETERINARIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_ITEM_VETERINARIOSActionPerformed
        // DesktopPaneControl.removeAll();
        Painel_Veterinarios_JIFF obj = new Painel_Veterinarios_JIFF();
        DesktopPaneControl.add(obj).setVisible(true);
    }//GEN-LAST:event_MENU_ITEM_VETERINARIOSActionPerformed

    private void BOTAO_SAIR___ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAO_SAIR___ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BOTAO_SAIR___ActionPerformed

    private void BOTAO_CADASTRO_VETERINARIO___ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAO_CADASTRO_VETERINARIO___ActionPerformed
        Painel_Veterinarios_JIFF obj = new Painel_Veterinarios_JIFF();
        DesktopPaneControl.add(obj).setVisible(true);
    }//GEN-LAST:event_BOTAO_CADASTRO_VETERINARIO___ActionPerformed

    private void BOTAO_CADASTRO_TUTOR___ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAO_CADASTRO_TUTOR___ActionPerformed
        Painel_Tutores_JIFF obj = new Painel_Tutores_JIFF();
        DesktopPaneControl.add(obj).setVisible(true);
    }//GEN-LAST:event_BOTAO_CADASTRO_TUTOR___ActionPerformed

    private void BOTAO_CADASTRO_PET___ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAO_CADASTRO_PET___ActionPerformed
        Painel_Pets_JIFF obj = new Painel_Pets_JIFF();
        DesktopPaneControl.add(obj).setVisible(true);
    }//GEN-LAST:event_BOTAO_CADASTRO_PET___ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Swing_Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Swing_Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Swing_Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Swing_Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Swing_Tela_Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTAO_CADASTRO_PET___;
    private javax.swing.JButton BOTAO_CADASTRO_TUTOR___;
    private javax.swing.JButton BOTAO_CADASTRO_VETERINARIO___;
    private javax.swing.JButton BOTAO_SAIR___;
    private javax.swing.JDesktopPane DesktopPaneControl;
    private javax.swing.JMenu MENU_HEADDER_BUTTON;
    private javax.swing.JMenu MENU_HEADDER_PRECOS;
    private javax.swing.JMenuItem MENU_ITEM_PETS;
    private javax.swing.JMenuItem MENU_ITEM_PRECOS;
    private javax.swing.JMenuItem MENU_ITEM_SAIR;
    private javax.swing.JMenuItem MENU_ITEM_TUTORES;
    private javax.swing.JMenuItem MENU_ITEM_VETERINARIOS;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
